version: '3.8'

services:
  client:
    depends_on:
      - server
    networks:
      - mern-app

  server:
    build:
      context: ./Server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGO_DB=mongodb://mongo:27017/social-media-app
    volumes:
      - ./Server/images:/app/images
    networks:
      - mern-app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

# Networks
networks:
  mern-app:
    driver: bridge

# Volumes
volumes:
  mongo-data:
    driver: local 